using System.ComponentModel.DataAnnotations.Schema;

namespace CenterReport.Repository.Models
{

    [Table("SourceData")]
    public class SourceData
    {
        public long Id { get; set; }
        public DateTime createdtime { get; set; } = DateTime.Now;
        public int Type { get; set; } = 0;
        public int PH { get; set; }
        public float? cell1 { get; set; }
        public float? cell2 { get; set; }
        public float? cell3 { get; set; }
        public float? cell4 { get; set; }
        public float? cell5 { get; set; }
        public float? cell6 { get; set; }
        public float? cell7 { get; set; }
        public float? cell8 { get; set; }
        public float? cell9 { get; set; }
        public float? cell10 { get; set; }
        public float? cell11 { get; set; }
        public float? cell12 { get; set; }
        public float? cell13 { get; set; }
        public float? cell14 { get; set; }
        public float? cell15 { get; set; }
        public float? cell16 { get; set; }
        public float? cell17 { get; set; }
        public float? cell18 { get; set; }
        public float? cell19 { get; set; }
        public float? cell20 { get; set; }
        public float? cell21 { get; set; }
        public float? cell22 { get; set; }
        public float? cell23 { get; set; }
        public float? cell24 { get; set; }
        public float? cell25 { get; set; }
        public float? cell26 { get; set; }
        public float? cell27 { get; set; }
        public float? cell28 { get; set; }
        public float? cell29 { get; set; }
        public float? cell30 { get; set; }
        public float? cell31 { get; set; }
        public float? cell32 { get; set; }
        public float? cell33 { get; set; }
        public float? cell34 { get; set; }
        public float? cell35 { get; set; }
        public float? cell36 { get; set; }
        public float? cell37 { get; set; }
        public float? cell38 { get; set; }
        public float? cell39 { get; set; }
        public float? cell40 { get; set; }
        public float? cell41 { get; set; }
        public float? cell42 { get; set; }
        public float? cell43 { get; set; }
        public float? cell44 { get; set; }
        public float? cell45 { get; set; }
        public float? cell46 { get; set; }
        public float? cell47 { get; set; }
        public float? cell48 { get; set; }
        public float? cell49 { get; set; }
        public float? cell50 { get; set; }
        public float? cell51 { get; set; }
        public float? cell52 { get; set; }
        public float? cell53 { get; set; }
        public float? cell54 { get; set; }
        public float? cell55 { get; set; }
        public float? cell56 { get; set; }
        public float? cell57 { get; set; }
        public float? cell58 { get; set; }
        public float? cell59 { get; set; }
        public float? cell60 { get; set; }
        public float? cell61 { get; set; }
        public float? cell62 { get; set; }
        public float? cell63 { get; set; }
        public float? cell64 { get; set; }
        public float? cell65 { get; set; }
        public float? cell66 { get; set; }
        public float? cell67 { get; set; }
        public float? cell68 { get; set; }
        public float? cell69 { get; set; }
        public float? cell70 { get; set; }
        public float? cell71 { get; set; }
        public float? cell72 { get; set; }
        public float? cell73 { get; set; }
        public float? cell74 { get; set; }
        public float? cell75 { get; set; }
        public float? cell76 { get; set; }
        public float? cell77 { get; set; }
        public float? cell78 { get; set; }
        public float? cell79 { get; set; }
        public float? cell80 { get; set; }
        public float? cell81 { get; set; }
        public float? cell82 { get; set; }
        public float? cell83 { get; set; }
        public float? cell84 { get; set; }
        public float? cell85 { get; set; }
        public float? cell86 { get; set; }
        public float? cell87 { get; set; }
        public float? cell88 { get; set; }
        public float? cell89 { get; set; }
        public float? cell90 { get; set; }
        public float? cell91 { get; set; }
        public float? cell92 { get; set; }
        public float? cell93 { get; set; }
        public float? cell94 { get; set; }
        public float? cell95 { get; set; }
        public float? cell96 { get; set; }
        public float? cell97 { get; set; }
        public float? cell98 { get; set; }
        public float? cell99 { get; set; }
        public float? cell100 { get; set; }
        public float? cell101 { get; set; }
        public float? cell102 { get; set; }
        public float? cell103 { get; set; }
        public float? cell104 { get; set; }
        public float? cell105 { get; set; }
        public float? cell106 { get; set; }
        public float? cell107 { get; set; }
        public float? cell108 { get; set; }
        public float? cell109 { get; set; }
        public float? cell110 { get; set; }
        public float? cell111 { get; set; }
        public float? cell112 { get; set; }
        public float? cell113 { get; set; }
        public float? cell114 { get; set; }
        public float? cell115 { get; set; }
        public float? cell116 { get; set; }
        public float? cell117 { get; set; }
        public float? cell118 { get; set; }
        public float? cell119 { get; set; }
        public float? cell120 { get; set; }
        public float? cell121 { get; set; }
        public float? cell122 { get; set; }
        public float? cell123 { get; set; }
        public float? cell124 { get; set; }
        public float? cell125 { get; set; }
        public float? cell126 { get; set; }
        public float? cell127 { get; set; }
        public float? cell128 { get; set; }
        public float? cell129 { get; set; }
        public float? cell130 { get; set; }
        public float? cell131 { get; set; }
        public float? cell132 { get; set; }
        public float? cell133 { get; set; }
        public float? cell134 { get; set; }
        public float? cell135 { get; set; }
        public float? cell136 { get; set; }
        public float? cell137 { get; set; }
        public float? cell138 { get; set; }
        public float? cell139 { get; set; }
        public float? cell140 { get; set; }
        public float? cell141 { get; set; }
        public float? cell142 { get; set; }
        public float? cell143 { get; set; }
        public float? cell144 { get; set; }
        public float? cell145 { get; set; }
        public float? cell146 { get; set; }
        public float? cell147 { get; set; }
        public float? cell148 { get; set; }
        public float? cell149 { get; set; }
        public float? cell150 { get; set; }
    }
}

